services:
  postgres:
    image: 'postgres:13.3'
    environment:
      - 'POSTGRES_DB=food-delivery-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'


#  spring-app:
#    image: 'serene_cannon'
#    depends_on:
#      - postgres
#    ports:
#      - '8080:8080'
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/food_delivery_db
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: password
