version: '3.8'

services:
  postgres:
    image: 'postgres:13.3'
    environment:
      - 'POSTGRES_DB=food-delivery-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - mynetwork

  springboot-app:
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:
